version: '3.7'

services:

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend/app:/srv/www
      - ./frontend/scripts:/scripts
    command: /scripts/init.sh
    ports:
      - "5000:5000"
    tty: true

  api:
    container_name: api
    build: ./api
    env_file:
      - .env
    volumes:
      - ./api/app:/srv/www
      - ./api/scripts:/scripts
    command: /scripts/init.sh
    ports:
      - "8080:8080"
    tty: true

  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/database:/bitnami
